### ISSUE TITLE
Except is not an optional Function, and cannot take a TypeMatcher comparison (isA<>())

### ISSUE THREAD

**Issue by Ivaskuu** [danijel-tolj/state_notifier_test#4]
Hi there! I run in a little problem while trying to create a test for my UserNotifier (StateNotifier).

This is the constructor of `stateNotifierTest`:
```
void stateNotifierTest<SN extends StateNotifier<State>, State>(
  String description, {
  required FutureOr Function(SN stateNotifier) actions,
  FutureOr<void> Function()? setUp,
  FutureOr<void> Function(SN stateNotifier)? verify,
  FutureOr<void> Function()? tearDown,
  required List<State> Function() expect,
  Iterable<State> Function()? seed,
  int skip = 0,
  required SN Function() build,
  dynamic Function()? errors,
  bool expectInitialState = false,
}) { ...
```

You mentioned in the comment above that we can use `expect` with `isA<>()` type matcher, but it is not possible with the current constructor declaration.

```
/// **Note:** when using [stateNotifierTest] with state classes which don't override
/// `==` and `hashCode` you can provide an `Iterable` of matchers instead of
/// explicit state instances.
///
/// ```dart
/// stateNotifierTest(
///  'emits [StateB] when EventB is called',
///  build: () => MyBloc(),
///  action: (stateNotifier) => stateNotifier.add(EventB()),
///  expect: () => [isA<StateB>()],
/// );
/// ```
```

So while trying to start the test like this:
```
stateNotifierTest<UserNotifier, AsyncValue<User?>>(
  'returns error when trying to edit a null user',
  expectInitialState: false,
  build: () => UserNotifier(
    userId: null,
    userRepository: mockUserRepository,
  ),
  actions: (un) {
    un.editUser(user1);
  },
  expect: () => [isA<AsyncError>()],
);
```

I get this error
<img width="1086" alt="Screenshot 2022-12-10 alle 13 16 23" src="https://user-images.githubusercontent.com/28832159/206854652-243358ff-1d69-4022-9159-0ac92e529f38.png">

Removing the type doesn't work either.
<img width="900" alt="Screenshot 2022-12-10 alle 13 17 23" src="https://user-images.githubusercontent.com/28832159/206854702-224c21b2-e7bd-4f9e-8d8c-bd4917aaca11.png">

I think being able to pass `isA<>() `would be very useful, since I have the `editUser` method that returns an `AsyncValue.error`, which requires the error object and also the current `StackTrace`, which is impossible to recreate as an object.
I saw that there is an errors parameter, but still, since expect is required and must match exactly the test will fail.

Thank you!

**Comment by danijel-tolj** [comment]
Sorry for the late response, the request is added in the latest version
